# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# based on: https://github.com/actions/starter-workflows/blob/b2e786d4e9af21f57ab07c1bc7231ed867f7675f/ci/node.js.yml

name: CI test with quick workaround - Node.js 17(+)

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
        - 17.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    # using cross-env NODE_OPTIONS=--openssl-legacy-provider as a quick &
    # hopefully temporary workaround for build issue from Node.js 17 ref:
    # - https://github.com/react-recompose/react-recompose/issues/13
    # - https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported/69699772#69699772
    # - https://github.com/webpack/webpack/issues/14532#issuecomment-947012063
    - run: npx cross-env NODE_OPTIONS=--openssl-legacy-provider npm test
